version: '2'
services:
  nginx-proxy:
    image: docker.io/cheminfo/eln-nginx-proxy
    ports:
      # Map application to local port
      # It is better to use in apache a Proxy from port 80 to port 4444 in order
      # also to setup easily a certificate
      # You should not change the container port number ! In this case 80.
      - '4444:80'
    links:
      - rest-on-couch
      - flavor-builder
      - printer-proxy
    #Uncomment to add web assets
    volumes:
      - ./nginx-proxy/conf.nginx:/etc/nginx/conf.d/default.conf
      - ./www:/data/www/

  couchdb:
    image: docker.io/apache/couchdb:2.1.0
    ports:
      - '4445:5984'
    environment:
      # CouchDB admin credentials
      COUCHDB_USER: admin # Do not change
      COUCHDB_PASSWORD: password # CHANGE HERE
    volumes:
      # Map local CouchDB data directory. You should not change the container directory !
      # in this case: /opt/couchdb/data
      - ./couchdb-data:/opt/couchdb/data
      - ./couchdb/local.ini:/opt/couchdb/etc/local.d/local.ini

  rest-on-couch:
    build: ./rest-on-couch
    environment:
      # CouchDB admin credentials
      # They must be the same as in the "couchdb" container
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password # CHANGE HERE. Must be the same as before
      COUCHDB_PRINTER_PASSWORD: password2 # CHANGE HERE. This password must not be the same as the admin password
      DEBUG: 'couch:error,couch:warn,couch:debug'
      REST_ON_COUCH_SESSION_KEY: koa:replace_me # CHANGE HERE. change 'replace_me' with 'openssl rand -hex 16'.
    expose:
      - 3000
    volumes:
    # Map local roc home directory
      - ./rest-on-couch-home:/rest-on-couch
      - ./pm2-rest-on-couch.yaml:/pm2-rest-on-couch.yaml
    links:
      - couchdb

  rest-on-couch-import:
    build: ./rest-on-couch
    command: pm2-docker start /pm2-roc-import.yaml
    environment:
      DEBUG: 'couch:error,couch:warn,couch:debug'
      REST_ON_COUCH_LOG_LEVEL: 'FATAL'
    volumes:
    # Map local roc home directory
      - ./rest-on-couch-home:/rest-on-couch
      - ./pm2-roc-import.yaml:/pm2-roc-import.yaml
    links:
      - couchdb

#  To enable the service, uncomment here and edit ./nginx-proxy/conf.nginx
#  rest-on-couch-file-drop:
#    build: ./rest-on-couch
#    command: pm2-docker start /pm2-roc-file-drop.yaml
#    environment:
#      DEBUG: 'couch:error,couch:warn,couch:debug'
#    volumes:
#      # Map local roc home directory
#      - ./rest-on-couch-home:/rest-on-couch
#      - ./pm2-roc-file-drop.yaml:/pm2-roc-file-drop.yaml
#    links:
#      - couchdb
#    expose:
#      - 3001

  flavor-builder:
    image: docker.io/cheminfo/eln-flavor-builder
    environment:
      DEBUG: 'flavor-builder*'
      # CouchDB admin credentials
      # They must be the same as in the "couchdb" container
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password # CHANGE HERE. Must be the same as before
    volumes:
      - ./www:/var/www/html/
    # Uncomment to use a custom flavor-builder config
    # This is usually unnecessary
    #  - ./flavor-config.json:/flavor-config.json
    links:
      - couchdb

  printer-proxy:
    image: docker.io/cheminfo/eln-printer-proxy
    command: pm2-docker start /pm2-proxy.yml
    volumes:
      - ./printer-proxy-config.yml:/config.yml
    links:
      - rest-on-couch
    expose:
      - 7770
